import {
  Certificate,
  Company,
  Invoice,
  Ngo,
  Opportunity,
  Report,
  ScheduleVII,
  Thread,
  User,
  VerificationQueueItem,
  Dispute,
  AuditEntry,
  PlanTier,
} from "./types";

export const currentUser: User = {
  id: "u-volunteer",
  name: "Aditi Sharma",
  email: "aditi.sharma@nexora.in",
  role: "volunteer",
  companyId: "co-nexora",
  skills: ["Teaching", "English", "Data analysis", "Design", "Social media"],
  location: "Pune",
  verified: true,
  hoursLogged: 74,
  languages: ["en", "hi", "ta"],
};

export const companies: Company[] = [
  {
    id: "co-nexora",
    name: "Nexora Technologies",
    industry: "Software & IT Services",
    employeeCount: 1284,
    csrBudgetAnnual: 42000000,
    budgetCommitted: 28500000,
    planTier: "growth",
    renewalDate: "2026-03-31",
    seatsIncluded: 1000,
    deptTargets: [
      { department: "Engineering", hoursTarget: 1200, hoursDone: 1045, budget: 12000000 },
      { department: "Product", hoursTarget: 600, hoursDone: 380, budget: 6000000 },
      { department: "Sales", hoursTarget: 800, hoursDone: 920, budget: 8000000 },
      { department: "Operations", hoursTarget: 400, hoursDone: 290, budget: 4000000 },
      { department: "People Ops", hoursTarget: 500, hoursDone: 410, budget: 5000000 },
    ],
    scheduleVIIAllocation: {
      education: 12000000,
      health: 7000000,
      environment: 5000000,
      livelihood: 6000000,
      disaster_relief: 4000000,
      heritage: 2000000,
      gender: 2000000,
      hunger: 3000000,
      sports: 0,
      other: 1000000,
    },
  },
  {
    id: "co-vaartha",
    name: "Vaartha Financial",
    industry: "Financial Services",
    employeeCount: 640,
    csrBudgetAnnual: 18000000,
    budgetCommitted: 6200000,
    planTier: "starter",
    renewalDate: "2026-06-30",
    seatsIncluded: 200,
    deptTargets: [
      { department: "Risk", hoursTarget: 300, hoursDone: 140, budget: 3000000 },
      { department: "Wealth", hoursTarget: 250, hoursDone: 90, budget: 2500000 },
    ],
    scheduleVIIAllocation: {
      education: 4000000,
      health: 3000000,
      environment: 2000000,
      livelihood: 3000000,
      disaster_relief: 0,
      heritage: 0,
      gender: 2000000,
      hunger: 2000000,
      sports: 0,
      other: 2000000,
    },
  },
];

export const ngos: Ngo[] = [
  {
    id: "ngo-siksha",
    name: "Siksha Setu Foundation",
    registrationNo: "MH/2022/0012345",
    location: "Pune",
    state: "Maharashtra",
    founded: 2015,
    focus: ["education", "gender"],
    verificationStatus: "verified",
    csrReadyScore: 92,
    scoreBreakdown: [
      { label: "Document completeness", value: 40, max: 40 },
      { label: "Document validity", value: 27, max: 30 },
      { label: "Impact track record", value: 17, max: 20 },
      { label: "Manual review", value: 8, max: 10 },
    ],
    documents: [
      {
        id: "doc-12a",
        type: "12A",
        name: "12A Registration Certificate",
        regNumber: "AAC-12A/2022/1147",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2025-08-12",
      },
      {
        id: "doc-80g",
        type: "80G",
        name: "80G Deduction Certificate",
        regNumber: "80G/2023/0881",
        validity: "2028-06-30",
        status: "valid",
        uploadedAt: "2025-08-12",
      },
      {
        id: "doc-fcra",
        type: "FCRA",
        name: "FCRA Registration",
        regNumber: "084521556",
        validity: "2026-09-14",
        status: "expiring",
        uploadedAt: "2025-08-12",
      },
    ],
    impactHistory: [
      { period: "FY 2023-24", beneficiaries: 12400, projects: 18 },
      { period: "FY 2024-25", beneficiaries: 18300, projects: 26 },
      { period: "FY 2025-26", beneficiaries: 24100, projects: 31 },
    ],
    headline: "Digital literacy for girls in low-income schools across Pune.",
    description:
      "Siksha Setu runs after-school digital literacy and STEM programs for 9,000+ girls across 44 municipal schools in Pune, with a demonstrated 3-year impact track record.",
    verifiedDate: "2025-09-02",
  },
  {
    id: "ngo-paani",
    name: "Paani Mitra Collective",
    registrationNo: "KA/2018/0044221",
    location: "Belagavi",
    state: "Karnataka",
    founded: 2011,
    focus: ["environment", "livelihood"],
    verificationStatus: "verified",
    csrReadyScore: 86,
    scoreBreakdown: [
      { label: "Document completeness", value: 38, max: 40 },
      { label: "Document validity", value: 25, max: 30 },
      { label: "Impact track record", value: 16, max: 20 },
      { label: "Manual review", value: 7, max: 10 },
    ],
    documents: [
      {
        id: "doc-p1",
        type: "12A",
        name: "12A Registration Certificate",
        regNumber: "AAC-12A/2019/3310",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2025-10-04",
      },
      {
        id: "doc-p2",
        type: "80G",
        name: "80G Deduction Certificate",
        regNumber: "80G/2021/0452",
        validity: "2027-03-31",
        status: "valid",
        uploadedAt: "2025-10-04",
      },
    ],
    impactHistory: [
      { period: "FY 2023-24", beneficiaries: 6400, projects: 9 },
      { period: "FY 2024-25", beneficiaries: 8800, projects: 13 },
      { period: "FY 2025-26", beneficiaries: 11200, projects: 17 },
    ],
    headline: "Rainwater harvesting and watershed restoration for drought-prone villages.",
    description:
      "Paani Mitra designs and maintains community watershed systems across 38 villages in northern Karnataka, restoring groundwater and farm livelihoods.",
    verifiedDate: "2025-11-01",
  },
  {
    id: "ngo-arogya",
    name: "Arogya Gram Network",
    registrationNo: "TN/2020/0098120",
    location: "Coimbatore",
    state: "Tamil Nadu",
    founded: 2016,
    focus: ["health", "hunger"],
    verificationStatus: "verified",
    csrReadyScore: 79,
    scoreBreakdown: [
      { label: "Document completeness", value: 34, max: 40 },
      { label: "Document validity", value: 22, max: 30 },
      { label: "Impact track record", value: 16, max: 20 },
      { label: "Manual review", value: 7, max: 10 },
    ],
    documents: [
      {
        id: "doc-a1",
        type: "12A",
        name: "12A Registration Certificate",
        regNumber: "AAC-12A/2020/5541",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2025-11-20",
      },
      {
        id: "doc-a2",
        type: "80G",
        name: "80G Deduction Certificate",
        regNumber: "80G/2021/1776",
        validity: "2029-01-31",
        status: "valid",
        uploadedAt: "2025-11-20",
      },
      {
        id: "doc-a3",
        type: "NITI Aayog",
        name: "NITI Aayog Registration",
        regNumber: "TN/2020/002",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2025-11-20",
      },
    ],
    impactHistory: [
      { period: "FY 2023-24", beneficiaries: 4800, projects: 7 },
      { period: "FY 2024-25", beneficiaries: 6900, projects: 11 },
      { period: "FY 2025-26", beneficiaries: 8300, projects: 14 },
    ],
    headline: "Mobile health camps and nutrition drives for rural communities.",
    description:
      "Arogya Gram runs mobile primary-care camps and community nutrition programs for 8,000+ people across rural Coimbatore and Pollachi.",
    verifiedDate: "2025-12-05",
  },
  {
    id: "ngo-udaya",
    name: "Udaya Women's Cooperative",
    registrationNo: "RJ/2019/0032177",
    location: "Jaipur",
    state: "Rajasthan",
    founded: 2013,
    focus: ["livelihood", "gender"],
    verificationStatus: "pending",
    csrReadyScore: 61,
    scoreBreakdown: [
      { label: "Document completeness", value: 24, max: 40 },
      { label: "Document validity", value: 18, max: 30 },
      { label: "Impact track record", value: 13, max: 20 },
      { label: "Manual review", value: 6, max: 10 },
    ],
    documents: [
      {
        id: "doc-u1",
        type: "12A",
        name: "12A Registration Certificate",
        regNumber: "AAC-12A/2020/7712",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2026-01-12",
      },
      {
        id: "doc-u2",
        type: "80G",
        name: "80G Application (Draft)",
        regNumber: "PENDING",
        validity: "—",
        status: "under_review",
        uploadedAt: "2026-01-12",
      },
      {
        id: "doc-u3",
        type: "PAN",
        name: "PAN Card",
        regNumber: "AAQCU8842M",
        validity: "Permanent",
        status: "valid",
        uploadedAt: "2026-01-12",
      },
    ],
    impactHistory: [
      { period: "FY 2023-24", beneficiaries: 2100, projects: 4 },
      { period: "FY 2024-25", beneficiaries: 3400, projects: 6 },
      { period: "FY 2025-26", beneficiaries: 4100, projects: 7 },
    ],
    headline: "Women-led artisan livelihoods and financial literacy in Jaipur.",
    description:
      "Udaya organizes 600+ women artisans into producer cooperatives, with skill training and market access for handicrafts.",
  },
  {
    id: "ngo-harith",
    name: "Harith Vana Trust",
    registrationNo: "AP/2017/0066110",
    location: "Vijayawada",
    state: "Andhra Pradesh",
    founded: 2010,
    focus: ["environment", "livelihood"],
    verificationStatus: "rejected",
    csrReadyScore: 38,
    scoreBreakdown: [
      { label: "Document completeness", value: 12, max: 40 },
      { label: "Document validity", value: 12, max: 30 },
      { label: "Impact track record", value: 8, max: 20 },
      { label: "Manual review", value: 6, max: 10 },
    ],
    documents: [
      {
        id: "doc-h1",
        type: "80G",
        name: "80G Certificate (Expired)",
        regNumber: "80G/2018/0033",
        validity: "2023-03-31",
        status: "expired",
        uploadedAt: "2025-12-01",
      },
    ],
    impactHistory: [
      { period: "FY 2023-24", beneficiaries: 900, projects: 2 },
      { period: "FY 2024-25", beneficiaries: 1100, projects: 3 },
    ],
    headline: "Urban tree plantation and green-lung drives in Vijayawada.",
    description: "Pending renewal of 80G registration before re-verification.",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Digital literacy mentor for after-school STEM clubs",
    ngoName: "Siksha Setu Foundation",
    ngoId: "ngo-siksha",
    category: "education",
    type: "long_term",
    duration: "10 weeks",
    location: "Pune",
    remote: false,
    slots: { total: 24, filled: 17 },
    hours: 30,
    skills: ["Teaching", "English", "Technology"],
    description:
      "Mentor groups of 4-5 girls through our after-school coding and digital literacy curriculum. 2 hours every Saturday at partner schools in Kothrud & Hadapsar.",
    lifecycle: "in_progress",
    sponsored: true,
    companyName: "Nexora Technologies",
    budget: 2400000,
    postedDate: "2026-01-05",
    recommendedScore: 94,
    matchReasons: ["94% skill overlap", "10 min from you", "Company match: Nexora"],
  },
  {
    id: "opp-2",
    title: "Design a micro-course on financial literacy",
    ngoName: "Udaya Women's Cooperative",
    ngoId: "ngo-udaya",
    category: "livelihood",
    type: "micro_task",
    duration: "6-8 hours, remote",
    location: "Remote",
    remote: true,
    slots: { total: 6, filled: 3 },
    hours: 8,
    skills: ["Design", "Content writing", "Financial literacy"],
    description:
      "Create a 5-module illustrated course on saving, budgeting and UPI safety for women artisan cooperatives. Deliverables reviewed by our training team.",
    lifecycle: "published",
    sponsored: false,
    postedDate: "2026-02-18",
    recommendedScore: 88,
    matchReasons: ["88% skill overlap", "Remote task", "2-5 hour bite-size"],
  },
  {
    id: "opp-3",
    title: "Watershed survey & data tagging",
    ngoName: "Paani Mitra Collective",
    ngoId: "ngo-paani",
    category: "environment",
    type: "micro_task",
    duration: "4-6 hours, remote",
    location: "Remote",
    remote: true,
    slots: { total: 12, filled: 9 },
    hours: 5,
    skills: ["Data analysis", "Excel", "GIS"],
    description:
      "Help clean and tag field survey data from 38 watershed villages. GIS experience a plus but not required — we provide tooling.",
    lifecycle: "in_progress",
    sponsored: true,
    companyName: "Vaartha Financial",
    budget: 900000,
    postedDate: "2026-02-02",
    recommendedScore: 76,
    matchReasons: ["76% skill overlap", "Remote task"],
  },
  {
    id: "opp-4",
    title: "Health camp registration & triage support",
    ngoName: "Arogya Gram Network",
    ngoId: "ngo-arogya",
    category: "health",
    type: "long_term",
    duration: "6 weeks",
    location: "Coimbatore",
    remote: false,
    slots: { total: 16, filled: 16 },
    hours: 24,
    skills: ["Communication", "Tamil", "Organisation"],
    description:
      "Support registration and patient-flow at weekend mobile health camps across rural Coimbatore. Tamil fluency required.",
    lifecycle: "closed",
    sponsored: false,
    postedDate: "2025-12-10",
  },
  {
    id: "opp-5",
    title: "Fundraising deck for girl-child education",
    ngoName: "Siksha Setu Foundation",
    ngoId: "ngo-siksha",
    category: "education",
    type: "micro_task",
    duration: "8-10 hours, remote",
    location: "Remote",
    remote: true,
    slots: { total: 4, filled: 1 },
    hours: 10,
    skills: ["Design", "Storytelling", "Data analysis"],
    description:
      "Turn our impact dashboard into a crisp 12-slide pitch deck for corporate CSR committees. We provide all data and brand assets.",
    lifecycle: "published",
    sponsored: true,
    companyName: "Nexora Technologies",
    budget: 1500000,
    postedDate: "2026-02-20",
    recommendedScore: 82,
    matchReasons: ["82% skill overlap", "Remote task"],
  },
  {
    id: "opp-6",
    title: "Nutrition drive packing & logistics",
    ngoName: "Arogya Gram Network",
    ngoId: "ngo-arogya",
    category: "hunger",
    type: "long_term",
    duration: "3 weekends",
    location: "Coimbatore",
    remote: false,
    slots: { total: 40, filled: 12 },
    hours: 12,
    skills: ["Physical work", "Logistics", "Organisation"],
    description:
      "Pack and distribute monthly nutrition kits to 2,400 families. Weekend shifts with transport from Coimbatore city.",
    lifecycle: "published",
    sponsored: false,
    postedDate: "2026-02-14",
    recommendedScore: 61,
    matchReasons: ["Location match", "Open to all volunteers"],
  },
  {
    id: "opp-7",
    title: "Teacher training workshop assistant",
    ngoName: "Siksha Setu Foundation",
    ngoId: "ngo-siksha",
    category: "education",
    type: "long_term",
    duration: "4 weeks",
    location: "Pune",
    remote: false,
    slots: { total: 8, filled: 2 },
    hours: 16,
    skills: ["Teaching", "English", "Technology"],
    description:
      "Assist our master-trainers delivering tablet-based teaching methods to 120 government school teachers.",
    lifecycle: "published",
    sponsored: true,
    companyName: "Nexora Technologies",
    budget: 800000,
    postedDate: "2026-02-10",
    recommendedScore: 79,
    matchReasons: ["79% skill overlap", "Company match: Nexora"],
  },
  {
    id: "opp-8",
    title: "Village skill-training curriculum review",
    ngoName: "Paani Mitra Collective",
    ngoId: "ngo-paani",
    category: "livelihood",
    type: "micro_task",
    duration: "6-8 hours, remote",
    location: "Remote",
    remote: true,
    slots: { total: 5, filled: 0 },
    hours: 7,
    skills: ["Content writing", "Agriculture", "Design"],
    description:
      "Review and improve drip-irrigation training modules translated from Kannada. Flag gaps in clarity and safety guidance.",
    lifecycle: "draft",
    sponsored: false,
    postedDate: "2026-02-22",
  },
  {
    id: "opp-9",
    title: "Festival craft design sprint",
    ngoName: "Udaya Women's Cooperative",
    ngoId: "ngo-udaya",
    category: "heritage",
    type: "micro_task",
    duration: "10-12 hours, remote",
    location: "Remote",
    remote: true,
    slots: { total: 8, filled: 6 },
    hours: 12,
    skills: ["Design", "Illustration", "Social media"],
    description:
      "Design festive packaging and social media kits for artisan products. Help the cooperative go from local fairs to online retail.",
    lifecycle: "in_progress",
    sponsored: false,
    postedDate: "2026-01-28",
    recommendedScore: 70,
    matchReasons: ["70% skill overlap", "Remote task"],
  },
  {
    id: "opp-10",
    title: "STEM lab refurbishment drive",
    ngoName: "Siksha Setu Foundation",
    ngoId: "ngo-siksha",
    category: "education",
    type: "long_term",
    duration: "2 weekends",
    location: "Pune",
    remote: false,
    slots: { total: 30, filled: 4 },
    hours: 10,
    skills: ["Physical work", "Technology", "Organisation"],
    description:
      "Set up and inventory STEM lab kits across 12 municipal schools. Kickoff with orientation at our head office.",
    lifecycle: "draft",
    sponsored: true,
    companyName: "Nexora Technologies",
    budget: 600000,
    postedDate: "2026-02-24",
  },
];

export const certificates: Certificate[] = [
  {
    id: "cert-1",
    code: "KRD-7FX2-9QPT-44",
    volunteerName: "Aditi Sharma",
    ngoName: "Siksha Setu Foundation",
    opportunityTitle: "Digital literacy mentor for after-school STEM clubs",
    category: "education",
    hours: 30,
    issuedAt: "2026-03-14",
    isPremium: true,
    issuedBy: "Kards Verified Credentials",
  },
  {
    id: "cert-2",
    code: "KRD-3MZK-8HRL-21",
    volunteerName: "Aditi Sharma",
    ngoName: "Paani Mitra Collective",
    opportunityTitle: "Watershed survey & data tagging",
    category: "environment",
    hours: 5,
    issuedAt: "2025-11-20",
    isPremium: false,
    issuedBy: "Kards Verified Credentials",
  },
  {
    id: "cert-3",
    code: "KRD-9NBA-2CVD-88",
    volunteerName: "Aditi Sharma",
    ngoName: "Arogya Gram Network",
    opportunityTitle: "Health camp registration & triage support",
    category: "health",
    hours: 24,
    issuedAt: "2025-10-02",
    isPremium: false,
    issuedBy: "Kards Verified Credentials",
  },
];

export const threads: Thread[] = [
  {
    id: "thr-1",
    opportunityId: "opp-1",
    title: "Digital literacy mentor for after-school STEM clubs",
    ngoName: "Siksha Setu Foundation",
    participants: ["Aditi Sharma", "Meera Joshi (NGO)"],
    lastMessageAt: "2026-02-24T09:12:00Z",
    unread: 2,
    messages: [
      {
        id: "m1",
        threadId: "thr-1",
        sender: "Meera Joshi",
        senderRole: "ngo",
        body: "Hi Aditi, welcome to the Saturday STEM mentor cohort! Here's your school allotment: Dr. Ambedkar School, Kothrud. Orientation is this Saturday 10am.",
        at: "2026-02-20T08:00:00Z",
      },
      {
        id: "m2",
        threadId: "thr-1",
        sender: "Aditi Sharma",
        senderRole: "volunteer",
        body: "Perfect, thanks Meera! I'll be there. Should I bring my own laptop for the coding module?",
        at: "2026-02-20T10:30:00Z",
      },
      {
        id: "m3",
        threadId: "thr-1",
        sender: "Meera Joshi",
        senderRole: "ngo",
        body: "Yes please — we have a limited number of loaner devices. I've attached the lesson plan for weeks 1-3.",
        at: "2026-02-21T07:45:00Z",
        attachment: "lesson-plan-w1-3.pdf",
      },
      {
        id: "m4",
        threadId: "thr-1",
        sender: "Aditi Sharma",
        senderRole: "volunteer",
        body: "Got it. Also — 3 of the girls in my group asked about a Python mini-project. I'm happy to run it if the syllabus allows.",
        at: "2026-02-24T09:12:00Z",
      },
      {
        id: "m5",
        threadId: "thr-1",
        sender: "Meera Joshi",
        senderRole: "ngo",
        body: "That would be amazing. Let me check with the curriculum lead and confirm on the thread tomorrow.",
        at: "2026-02-24T11:02:00Z",
      },
    ],
  },
  {
    id: "thr-2",
    opportunityId: "opp-5",
    title: "Fundraising deck for girl-child education",
    ngoName: "Siksha Setu Foundation",
    participants: ["Aditi Sharma", "Rohan Gupta (NGO)"],
    lastMessageAt: "2026-02-22T14:00:00Z",
    unread: 0,
    messages: [
      {
        id: "n1",
        threadId: "thr-2",
        sender: "Rohan Gupta",
        senderRole: "ngo",
        body: "Thanks for taking the deck. Here's the impact data export and our brand folder.",
        at: "2026-02-22T13:00:00Z",
        attachment: "impact-data-export.csv",
      },
      {
        id: "n2",
        threadId: "thr-2",
        sender: "Aditi Sharma",
        senderRole: "volunteer",
        body: "Perfect, I'll have a first cut by Friday.",
        at: "2026-02-22T14:00:00Z",
      },
    ],
  },
];

export const reports: Report[] = [
  {
    id: "rep-1",
    period: "Q1 FY 2026",
    status: "ready",
    totalHours: 4860,
    totalBudgetDeployed: 12400000,
    volunteers: 342,
    ngoCount: 6,
    scheduleVIIBreakdown: [
      { category: "education", hours: 1860, budget: 4200000, volunteers: 128 },
      { category: "health", hours: 1040, budget: 2600000, volunteers: 74 },
      { category: "environment", hours: 820, budget: 1900000, volunteers: 61 },
      { category: "livelihood", hours: 640, budget: 1700000, volunteers: 44 },
      { category: "disaster_relief", hours: 300, budget: 1200000, volunteers: 22 },
      { category: "heritage", hours: 200, budget: 800000, volunteers: 13 },
    ],
    deptBreakdown: [
      { department: "Engineering", hours: 1210, budget: 3400000 },
      { department: "Product", hours: 610, budget: 1800000 },
      { department: "Sales", hours: 980, budget: 2600000 },
      { department: "Operations", hours: 540, budget: 1500000 },
      { department: "People Ops", hours: 1520, budget: 3100000 },
    ],
    generatedAt: "2026-01-02",
    downloaded: 14,
  },
  {
    id: "rep-2",
    period: "Q2 FY 2026",
    status: "generating",
    totalHours: 0,
    totalBudgetDeployed: 0,
    volunteers: 0,
    ngoCount: 0,
    scheduleVIIBreakdown: [],
    deptBreakdown: [],
    generatedAt: "2026-02-24",
    downloaded: 0,
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-1",
    number: "INV-2026-0081",
    period: "FY 2026-27 Annual",
    amount: 480000,
    status: "paid",
    dueDate: "2026-04-01",
    items: [
      { label: "Growth plan — annual subscription", amount: 480000 },
      { label: "Success fee (1.5% of deployed budget)", amount: 186000 },
    ],
  },
  {
    id: "inv-2",
    number: "INV-2026-0082",
    period: "Q3 FY 2026 usage",
    amount: 186000,
    status: "pending",
    dueDate: "2026-03-15",
    items: [{ label: "Success fee (1.5% of ₹1.24 Cr deployed)", amount: 186000 }],
  },
  {
    id: "inv-3",
    number: "INV-2025-0066",
    period: "Q1 FY 2026 usage",
    amount: 92000,
    status: "paid",
    dueDate: "2025-10-15",
    items: [{ label: "Success fee (1.5% of ₹61.3L deployed)", amount: 92000 }],
  },
];

export const verificationQueue: VerificationQueueItem[] = [
  {
    id: "vq-1",
    ngoName: "Udaya Women's Cooperative",
    location: "Jaipur, Rajasthan",
    submittedAt: "2026-02-20",
    docCount: 3,
    risk: "medium",
    status: "pending",
    priority: 2,
  },
  {
    id: "vq-2",
    ngoName: "Kisan Prerna Samiti",
    location: "Nagpur, Maharashtra",
    submittedAt: "2026-02-22",
    docCount: 2,
    risk: "low",
    status: "pending",
    priority: 1,
  },
  {
    id: "vq-3",
    ngoName: "Nari Shakti Kendra",
    location: "Gorakhpur, UP",
    submittedAt: "2026-02-23",
    docCount: 4,
    risk: "high",
    status: "pending",
    priority: 3,
  },
  {
    id: "vq-4",
    ngoName: "Harith Vana Trust",
    location: "Vijayawada, AP",
    submittedAt: "2026-02-18",
    docCount: 1,
    risk: "high",
    status: "rejected",
    priority: 3,
  },
];

export const disputes: Dispute[] = [
  {
    id: "dsp-1",
    title: "Hours discrepancy on certificate",
    from: "Volunteer: R. Krishnan",
    opportunityId: "opp-4",
    status: "open",
    at: "2026-02-21",
    summary: "Volunteer claims 24 logged hours but certificate reflects 18. NGO confirmed 3 shifts not 4.",
  },
  {
    id: "dsp-2",
    title: "Slot overbooking complaint",
    from: "NGO: Arogya Gram Network",
    opportunityId: "opp-6",
    status: "resolved",
    at: "2026-02-10",
    summary: "Resolved — slot cap enforced retroactively, waitlist invited.",
  },
];

export const auditLog: AuditEntry[] = [
  {
    id: "a1",
    actor: "admin@kards.app",
    action: "NGO verified",
    target: "Arogya Gram Network",
    reason: "All documents validated, past project track record confirmed",
    at: "2026-02-18T10:24:00Z",
    severity: "info",
  },
  {
    id: "a2",
    actor: "admin@kards.app",
    action: "Document expiry flagged",
    target: "Siksha Setu Foundation · FCRA",
    reason: "Auto-reminder: FCRA renews 2026-09-14",
    at: "2026-02-15T09:00:00Z",
    severity: "warning",
  },
  {
    id: "a3",
    actor: "company-csr@nexora.in",
    action: "Report generated",
    target: "Q1 FY 2026 compliance report",
    reason: "Manual generation by CSR lead",
    at: "2026-02-14T16:40:00Z",
    severity: "info",
  },
  {
    id: "a4",
    actor: "admin@kards.app",
    action: "NGO rejected",
    target: "Harith Vana Trust",
    reason: "80G expired; no revalidation submitted",
    at: "2026-02-12T12:10:00Z",
    severity: "critical",
  },
  {
    id: "a5",
    actor: "system",
    action: "Score recomputed",
    target: "Udaya Women's Cooperative",
    reason: "New 80G application attached",
    at: "2026-02-11T08:30:00Z",
    severity: "info",
  },
  {
    id: "a6",
    actor: "admin@kards.app",
    action: "Dispute resolved",
    target: "Slot overbooking · opp-6",
    reason: "Retroactive cap enforced",
    at: "2026-02-10T14:00:00Z",
    severity: "info",
  },
];

export const activityFeed = [
  {
    id: "af-1",
    title: "Application accepted — STEM mentor cohort",
    detail: "Siksha Setu Foundation accepted your application",
    at: "2026-02-20T08:00:00Z",
    kind: "accepted",
  },
  {
    id: "af-2",
    title: "New recommendation for you",
    detail: "Fundraising deck for girl-child education · 82% match",
    at: "2026-02-21T06:00:00Z",
    kind: "recommendation",
  },
  {
    id: "af-3",
    title: "Certificate issued",
    detail: "Watershed survey & data tagging · 5 hours",
    at: "2025-11-20T09:30:00Z",
    kind: "certificate",
  },
];

export const myApplications = [
  {
    id: "app-1",
    opportunityId: "opp-1",
    title: "Digital literacy mentor for after-school STEM clubs",
    ngoName: "Siksha Setu Foundation",
    status: "accepted",
    hoursLogged: 12,
    hoursTarget: 30,
    appliedAt: "2026-01-10",
  },
  {
    id: "app-2",
    opportunityId: "opp-5",
    title: "Fundraising deck for girl-child education",
    ngoName: "Siksha Setu Foundation",
    status: "in_review",
    hoursLogged: 0,
    hoursTarget: 10,
    appliedAt: "2026-02-21",
  },
  {
    id: "app-3",
    opportunityId: "opp-3",
    title: "Watershed survey & data tagging",
    ngoName: "Paani Mitra Collective",
    status: "completed",
    hoursLogged: 5,
    hoursTarget: 5,
    appliedAt: "2025-11-01",
  },
];

export const scheduleVIIAllocation: Record<ScheduleVII, { committed: number; utilized: number }> = {
  education: { committed: 12000000, utilized: 8200000 },
  health: { committed: 7000000, utilized: 4600000 },
  environment: { committed: 5000000, utilized: 3100000 },
  livelihood: { committed: 6000000, utilized: 3900000 },
  disaster_relief: { committed: 4000000, utilized: 1200000 },
  heritage: { committed: 2000000, utilized: 900000 },
  gender: { committed: 2000000, utilized: 1400000 },
  hunger: { committed: 3000000, utilized: 2200000 },
  sports: { committed: 0, utilized: 0 },
  other: { committed: 1000000, utilized: 500000 },
};

export const hoursTrend = [
  { month: "Apr", hours: 1200, budget: 2800000 },
  { month: "May", hours: 1480, budget: 3200000 },
  { month: "Jun", hours: 1120, budget: 2600000 },
  { month: "Jul", hours: 1680, budget: 3800000 },
  { month: "Aug", hours: 1940, budget: 4100000 },
  { month: "Sep", hours: 1760, budget: 3600000 },
  { month: "Oct", hours: 1320, budget: 2900000 },
  { month: "Nov", hours: 1480, budget: 3100000 },
  { month: "Dec", hours: 1620, budget: 3400000 },
  { month: "Jan", hours: 1890, budget: 4200000 },
  { month: "Feb", hours: 2040, budget: 4700000 },
];

export const teamMembers = [
  { id: "tm-1", name: "Aditi Sharma", dept: "Engineering", role: "Frontend Engineer", hours: 74, email: "aditi.sharma@nexora.in" },
  { id: "tm-2", name: "Ravi Iyer", dept: "Sales", role: "Account Executive", hours: 112, email: "ravi.iyer@nexora.in" },
  { id: "tm-3", name: "Priya Nair", dept: "Product", role: "Product Designer", hours: 48, email: "priya.nair@nexora.in" },
  { id: "tm-4", name: "Karan Mehta", dept: "Operations", role: "Ops Lead", hours: 26, email: "karan.mehta@nexora.in" },
  { id: "tm-5", name: "Sneha Rao", dept: "People Ops", role: "HRBP", hours: 91, email: "sneha.rao@nexora.in" },
  { id: "tm-6", name: "Arjun Nair", dept: "Engineering", role: "Backend Engineer", hours: 12, email: "arjun.nair@nexora.in" },
];

export const testimonials = [
  {
    name: "Meera Joshi",
    org: "Founder, Siksha Setu Foundation, Pune",
    quote:
      "We were invisible to corporate CSR budgets before Kards. Now our CSR-Ready Score is 92 and we closed ₹1.2 Cr in funding in one quarter.",
    metric: "₹1.2 Cr CSR funding closed",
  },
  {
    name: "Rohit Menon",
    org: "CSR Lead, Nexora Technologies",
    quote:
      "The board-ready Q1 report took me an afternoon instead of three weeks of spreadsheet archaeology. Auditors accepted it without a single follow-up.",
    metric: "0 audit queries in FY26",
  },
  {
    name: "Lakshmi Venkat",
    org: "Volunteer Coordinator, Arogya Gram",
    quote:
      "Documents that used to take us months to gather were organized into one verified profile. Re-verification reminders keep us compliant automatically.",
    metric: "3x faster to verified",
  },
  {
    name: "Vikram Singh",
    org: "Head of Sustainability, Vaartha Financial",
    quote:
      "We publish micro-tasks for our 600 employees and the matching engine does the rest. Department targets finally make sense on a dashboard.",
    metric: "340% more hours logged",
  },
];

export const stats = [
  { label: "NGOs verified & CSR-ready", value: 4120, suffix: "+" },
  { label: "Companies deploying CSR", value: 86, suffix: "" },
  { label: "Volunteer hours tracked", value: 320000, suffix: "+" },
  { label: "Compliance reports delivered", value: 1240, suffix: "" },
];

export const languageNames: Record<string, string> = {
  en: "English",
  hi: "हिन्दी",
  ta: "தமிழ்",
};

export function companyFor(planTier: PlanTier): Company {
  return companies.find((c) => c.planTier === planTier) ?? companies[0];
}
