"""initial schema

Revision ID: 9c9ff2e17d38
Revises: 
Create Date: 2026-08-02 14:46:08.123176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9c9ff2e17d38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_events',
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mail_events_to', 'mail_events', ['to_email', 'created_at'], unique=False)
    op.create_table('payment_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_payment_event')
    )
    op.create_table('plans',
    sa.Column('tier', sa.Enum('STARTER', 'GROWTH', 'ENTERPRISE', name='plantier', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_annual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('VOLUNTEER', 'NGO', 'COMPANY', 'ADMIN', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('locale', sa.Enum('EN', 'HI', 'TA', name='locale', native_enum=False, length=40), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_company', 'api_keys', ['company_user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditseverity', native_enum=False, length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_time', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_subject', 'audit_logs', ['subject_type', 'subject_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('cin', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_budgets',
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=9), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_user_id', 'fiscal_year', name='uq_budget_company_year')
    )
    op.create_table('csr_scores',
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('documents_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('operations_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('past_performance_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('governance_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('computed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ngo_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_csr_scores_ngo', 'csr_scores', ['ngo_user_id', 'created_at'], unique=False)
    op.create_table('disputes',
    sa.Column('subject_type', sa.Enum('CERTIFICATE', 'WORK_LOG', 'OPPORTUNITY', name='disputesubjecttype', native_enum=False, length=40), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('filed_by', sa.Uuid(), nullable=False),
    sa.Column('against_user_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'ESCALATED', name='disputestatus', native_enum=False, length=40), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['against_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_status', 'disputes', ['status', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('subject_type', sa.Enum('NGO_VERIFICATION', 'PROJECT_EVIDENCE', 'EXPENSE_RECEIPT', 'ATTENDANCE_SHEET', 'REPORT_ATTACHMENT', 'MESSAGE_ATTACHMENT', name='docsubjecttype', native_enum=False, length=40), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('doc_type', sa.Enum('FORM_12A', 'FORM_80G', 'FCRA', 'PAN', 'NITI_AAYOG', 'OTHER', name='doctype', native_enum=False, length=40), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', name='docvalidationstatus', native_enum=False, length=40), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_subject', 'documents', ['subject_type', 'subject_id'], unique=False)
    op.create_table('ngo_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('reg_number', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('APPLICATION', 'ACCEPTED', 'REJECTED', 'HOURS', 'CERTIFICATE', 'VERIFICATION', 'MESSAGE', 'PARTNERSHIP', 'SYSTEM', name='notificationtype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('projects',
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('EDUCATION', 'HEALTH', 'ENVIRONMENT', 'LIVELIHOOD', 'DISASTER_RELIEF', 'HERITAGE', 'GENDER', 'HUNGER', 'SPORTS', 'OTHER', name='schedulevii', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='projectstatus', native_enum=False, length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_company', 'projects', ['company_user_id', 'status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='subscriptionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_company', 'subscriptions', ['company_user_id', 'status'], unique=False)
    op.create_table('threads',
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'subject_id', name='uq_thread_subject')
    )
    op.create_index('ix_threads_updated', 'threads', ['last_message_at'], unique=False)
    op.create_table('tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('REFRESH', 'EMAIL_VERIFY', 'PASSWORD_RESET', name='tokenpurpose', native_enum=False, length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_family'), 'tokens', ['family'], unique=False)
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=False)
    op.create_index('ix_tokens_user_purpose', 'tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('verification_requests',
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ngo_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_requests_ngo_status', 'verification_requests', ['ngo_user_id', 'status'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('availability', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_budget_allocations',
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('EDUCATION', 'HEALTH', 'ENVIRONMENT', 'LIVELIHOOD', 'DISASTER_RELIEF', 'HERITAGE', 'GENDER', 'HUNGER', 'SPORTS', 'OTHER', name='schedulevii', native_enum=False, length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['csr_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'category', name='uq_allocation_budget_category')
    )
    op.create_table('invoices',
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='invoicestatus', native_enum=False, length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_invoice_id', name='uq_invoice_provider_id')
    )
    op.create_index('ix_invoices_company_status', 'invoices', ['company_user_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_key', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_thread', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('EDUCATION', 'HEALTH', 'ENVIRONMENT', 'LIVELIHOOD', 'DISASTER_RELIEF', 'HERITAGE', 'GENDER', 'HUNGER', 'SPORTS', 'OTHER', name='schedulevii', native_enum=False, length=40), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', name='opportunitystatus', native_enum=False, length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('slots_total', sa.Integer(), nullable=False),
    sa.Column('slots_filled', sa.Integer(), nullable=False),
    sa.Column('hours_estimate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ngo_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_ngo_status', 'opportunities', ['ngo_user_id', 'status'], unique=False)
    op.create_index('ix_opportunities_project', 'opportunities', ['project_id'], unique=False)
    op.create_table('project_partnerships',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', name='partnershipstatus', native_enum=False, length=40), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ngo_user_id', name='uq_partnership_project_ngo')
    )
    op.create_index('ix_partnerships_ngo_status', 'project_partnerships', ['ngo_user_id', 'status'], unique=False)
    op.create_table('reports',
    sa.Column('kind', sa.Enum('COMPLIANCE', 'PROJECT', name='reportkind', native_enum=False, length=40), nullable=False),
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'FAILED', name='reportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_volunteers', sa.Integer(), nullable=True),
    sa.Column('total_expense', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('schedule_vii_breakdown', sa.JSON(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_company_status', 'reports', ['company_user_id', 'status'], unique=False)
    op.create_table('thread_participants',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_participant')
    )
    op.create_table('applications',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('cover_note', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'volunteer_id', name='uq_application_opportunity_volunteer')
    )
    op.create_index('ix_applications_opportunity_status', 'applications', ['opportunity_id', 'status'], unique=False)
    op.create_index('ix_applications_volunteer_status', 'applications', ['volunteer_id', 'status'], unique=False)
    op.create_table('certificates',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('hours_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=False),
    sa.Column('template', sa.Enum('STANDARD', 'PREMIUM', name='certificatetemplate', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'REVOKED', name='certificatestatus', native_enum=False, length=40), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_code'), 'certificates', ['code'], unique=True)
    op.create_index('ix_certificates_volunteer', 'certificates', ['volunteer_id', 'status'], unique=False)
    op.create_table('work_logs',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='worklogstatus', native_enum=False, length=40), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'volunteer_id', 'log_date', name='uq_worklog_day')
    )
    op.create_index('ix_worklogs_opportunity_status', 'work_logs', ['opportunity_id', 'status'], unique=False)
    op.create_index('ix_worklogs_volunteer', 'work_logs', ['volunteer_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worklogs_volunteer', table_name='work_logs')
    op.drop_index('ix_worklogs_opportunity_status', table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index('ix_certificates_volunteer', table_name='certificates')
    op.drop_index(op.f('ix_certificates_code'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_applications_volunteer_status', table_name='applications')
    op.drop_index('ix_applications_opportunity_status', table_name='applications')
    op.drop_table('applications')
    op.drop_table('thread_participants')
    op.drop_index('ix_reports_company_status', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_partnerships_ngo_status', table_name='project_partnerships')
    op.drop_table('project_partnerships')
    op.drop_index('ix_opportunities_project', table_name='opportunities')
    op.drop_index('ix_opportunities_ngo_status', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_invoices_company_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('csr_budget_allocations')
    op.drop_table('volunteer_profiles')
    op.drop_index('ix_verification_requests_ngo_status', table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index('ix_tokens_user_purpose', table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_family'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('ix_threads_updated', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_subscriptions_company', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_projects_company', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('ngo_profiles')
    op.drop_index('ix_documents_subject', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_csr_scores_ngo', table_name='csr_scores')
    op.drop_table('csr_scores')
    op.drop_table('csr_budgets')
    op.drop_table('company_profiles')
    op.drop_index('ix_audit_subject', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index('ix_api_keys_company', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('payment_events')
    op.drop_index('ix_mail_events_to', table_name='mail_events')
    op.drop_table('mail_events')
    # ### end Alembic commands ###
